


CC=g++
FLAGS=-static -g -Wall -std=c++17
OUTPUT=program

INPUT=input.txt


ex1:
	$(CC) $(FLAGS) ex1.cpp -o $(OUTPUT)

ex2:
	$(CC) $(FLAGS) ex2.cpp -o $(OUTPUT)

ex3:
	$(CC) $(FLAGS) ex3.cpp -o $(OUTPUT)

ex4:
	$(CC) $(FLAGS) ex4.cpp -o $(OUTPUT)

ex5:
	$(CC) $(FLAGS) ex5.cpp -o $(OUTPUT)

ex6:
	$(CC) $(FLAGS) ex6.cpp -o $(OUTPUT)

ex7:
	$(CC) $(FLAGS) ex7.cpp -o $(OUTPUT)

teste:
	$(CC) $(FLAGS) teste.cpp -o $(OUTPUT)

run:
	@./$(OUTPUT) < $(INPUT)
